field_1_name:
  type: string
  default: ""
  description: "Name of the first user field to hide (leave blank to disable)"

field_1_allowed_groups:
  type: group_list
  default: ""
  description: "Groups that can see field 1"

field_2_name:
  type: string
  default: ""
  description: "Name of the second user field to hide (leave blank to disable)"

field_2_allowed_groups:
  type: group_list
  default: ""
  description: "Groups that can see field 2"

field_3_name:
  type: string
  default: ""
  description: "Name of the third user field to hide (leave blank to disable)"

field_3_allowed_groups:
  type: group_list
  default: ""
  description: "Groups that can see field 3"

field_4_name:
  type: string
  default: ""
  description: "Name of the fourth user field to hide (leave blank to disable)"

field_4_allowed_groups:
  type: group_list
  default: ""
  description: "Groups that can see field 4"

field_5_name:
  type: string
  default: ""
  description: "Name of the fifth user field to hide (leave blank to disable)"

field_5_allowed_groups:
  type: group_list
  default: ""
  description: "Groups that can see field 5"
